local defines = defines
local defines_prototypes = defines.prototypes
local pairs = pairs

local attack_group_constants = {}
attack_group_constants.types_list = {}
attack_group_constants.types_table = {}

for sub_type, _ in pairs(defines_prototypes or {}) do
    attack_group_constants.types_list[#attack_group_constants.types_list+1] = sub_type
    attack_group_constants.types_table[sub_type] = 1
end

-- attack_group_constants.type_blacklist = {
--     "arrow",
--     "artillery-flare",
--     "artillery-projectile",
--     "beam",
--     "cargo-pod",
--     "character-corpse",
--     "cliff",
--     "deconstructible-tile-proxy",
--     "electric-energy-interface",
--     "entity-ghost",
--     "explosion",
--     "fire",
--     "fish",
--     "heat-interface",
--     "highlight-box",
--     "infinity-cargo-wagon",
--     "infinity-container",
--     "infinity-pipe",
--     "item-request-proxy",
--     "lightning",
--     "particle-source",
--     "player-port",
--     "projectile",
--     "proxy-container",
--     "resource",
--     "rocket-silo-rocket",
--     "rocket-silo-rocket-shadow",
--     "segment",
--     "segmented-unit",
--     "smoke-with-trigger",
--     "speech-bubble",
--     "sticker",
--     "stream",
--     "temporary-container",
--     "tile-ghost",
-- }
attack_group_constants.type_blacklist = {
    -- "accumulator",
    -- "agricultural-tower",
    -- "ammo-turret",
    -- "arithmetic-combinator",
    "arrow",
    "artillery-flare",
    "artillery-projectile",
    -- "artillery-turret",
    -- "artillery-wagon",
    -- "assembling-machine",
    "asteroid",
    "asteroid-collector",
    -- "beacon",
    "beam",
    -- "boiler",
    -- "burner-generator",
    -- "capture-robot",
    -- "car",
    -- "cargo-bay",
    -- "cargo-landing-pad",
    "cargo-pod",
    -- "cargo-wagon",
    -- "character",
    -- "character-corpse",
    "cliff",
    -- "combat-robot",
    -- "constant-combinator",
    -- "construction-robot",
    -- "container",
    "corpse",
    -- "curved-rail-a",
    -- "curved-rail-b",
    -- "decider-combinator",
    "deconstructible-tile-proxy",
    -- "display-panel",
    "electric-energy-interface",
    -- "electric-pole",
    -- "electric-turret",
    -- "elevated-curved-rail-a",
    -- "elevated-curved-rail-b",
    -- "elevated-half-diagonal-rail",
    -- "elevated-straight-rail",
    "entity-ghost",
    "explosion",
    "fire",
    "fish",
    -- "fluid-turret",
    -- "fluid-wagon",
    -- "furnace",
    -- "fusion-generator",
    -- "fusion-reactor",
    -- "gate",
    -- "generator",
    -- "half-diagonal-rail",
    "heat-interface",
    -- "heat-pipe",
    "highlight-box",
    "infinity-cargo-wagon",
    "infinity-container",
    "infinity-pipe",
    -- "inserter",
    "item-entity",
    "item-request-proxy",
    -- "lab",
    -- "lamp",
    -- "land-mine",
    -- "lane-splitter",
    "legacy-curved-rail",
    "legacy-straight-rail",
    "lightning",
    -- "lightning-attractor",
    -- "linked-belt",
    "linked-container",
    "loader",
    "loader-1x1",
    -- "locomotive",
    -- "logistic-container",
    -- "logistic-robot",
    -- "market",
    -- "mining-drill",
    -- "offshore-pump",
    "particle-source",
    -- "pipe",
    -- "pipe-to-ground",
    "plant",
    "player-port",
    -- "power-switch",
    -- "programmable-speaker",
    "projectile",
    "proxy-container",
    -- "pump",
    -- "radar",
    -- "rail-chain-signal",
    -- "rail-ramp",
    "rail-remnants",
    -- "rail-signal",
    -- "rail-support",
    -- "reactor",
    "resource",
    -- "roboport",
    -- "rocket-silo",
    "rocket-silo-rocket",
    "rocket-silo-rocket-shadow",
    "segment",
    "segmented-unit",
    -- "selector-combinator",
    "simple-entity",
    -- "simple-entity-with-force",
    "simple-entity-with-owner",
    "smoke-with-trigger",
    -- "solar-panel",
    "space-platform-hub",
    "speech-bubble",
    "spider-leg",
    "spider-unit",
    -- "spider-vehicle",
    -- "splitter",
    "sticker",
    -- "storage-tank",
    -- "straight-rail",
    "stream",
    "temporary-container",
    "thruster",
    "tile-ghost",
    -- "train-stop",
    -- "transport-belt",
    "tree",
    -- "turret",
    -- "underground-belt",
    "unit",
    "unit-spawner",
    "valve",
    -- "wall"
}

attack_group_constants.type_blacklist_table = {}

for _, v in pairs(attack_group_constants.type_blacklist) do
    attack_group_constants.type_blacklist_table[v] = 1
end

attack_group_constants.type_whitelist = {}
attack_group_constants.type_whitelist_table = {}
for sub_type, _ in pairs(defines_prototypes or {}) do
    if (not attack_group_constants.type_blacklist_table[sub_type]) then
        attack_group_constants.type_whitelist[#attack_group_constants.type_whitelist+1] = sub_type
        attack_group_constants.type_whitelist_table[sub_type] = 1
    end
end

return attack_group_constants